name: Test task5

on:
  push:
    paths:
     - ".github/workflows/run_test_cw1.yaml"
     - "tasks/classTask1/main.cpp"
     - "tasks/classTask1/tests.py"
  pull_request:
    paths:
     - ".github/workflows/run_test_cw1.yaml"
     - "tasks/classTask1/main.cpp"
     - "tasks/classTask1/tests.py"


env:
  TASK_DIR: ${{github.workspace}}/tasks/classTask1/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      working-directory: ${{env.TASK_DIR}}
      run: make config

    - name: Build
      working-directory: ${{env.TASK_DIR}}
      run: make build

    - name: Tests
      working-directory: ${{env.TASK_DIR}}
      run: make test
      shell: bash
