name: Test task3

on:
  push:
    paths:
     - ".github/workflows/run_test_hw3.yaml"
     - "tasks/task3/bin_search.hpp"
     - "!tasks/task3/tests/**"
  pull_request:
    paths:
     - ".github/workflows/run_test_hw3.yaml"
     - "tasks/task3/bin_search.hpp"
     - "!tasks/task3/tests/**"


env:
  TASK_DIR: ${{github.workspace}}/tasks/task3/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      working-directory: ${{env.TASK_DIR}}
      run: make config

    - name: Build
      working-directory: ${{env.TASK_DIR}}
      run: make build

    - name: Tests
      working-directory: ${{env.TASK_DIR}}
      run: make test
      shell: bash