name: Test task2

on:
  push:
    paths:
     - ".github/workflows/run_test_hw2.yaml"
     - "tasks/task2/matrix.cpp"
     - "!tasks/task2/tests/**"
  pull_request:
    paths:
     - ".github/workflows/run_test_hw2.yaml"
     - "tasks/task2/matrix.cpp"
     - "!tasks/task2/tests/**"


env:
  TASK_DIR: ${{github.workspace}}/tasks/task2/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      working-directory: ${{env.TASK_DIR}}
      run: make config

    - name: Build
      working-directory: ${{env.TASK_DIR}}
      run: make build

    - name: Tests
      working-directory: ${{env.TASK_DIR}}
      run: make test
      shell: bash